#!/bin/sh
# teamctl installer — downloads the latest release tarballs for the current
# platform (one per binary: teamctl, team-mcp, team-bot), verifies sha256s,
# and drops the binaries in ~/.local/bin.
#
# Usage:
#     curl -fsSL https://teamctl.run/install | sh
#     curl -fsSL https://teamctl.run/install | sh -s -- --version v0.2.9
#
# Environment overrides:
#   TEAMCTL_INSTALL_DIR   target directory (default: ~/.local/bin)
#   TEAMCTL_VERSION       version tag to install (default: latest)
#   TEAMCTL_VERIFY        set to 0 to skip sha256 verification (offline/dev only)
#
# The production version of this script is generated by cargo-dist on every
# release and hosted at https://teamctl.run/install. This file is the source
# of truth for the fallback and for local installs.

set -eu

REPO="Alireza29675/teamctl"
INSTALL_DIR="${TEAMCTL_INSTALL_DIR:-$HOME/.local/bin}"
VERSION="${TEAMCTL_VERSION:-latest}"
VERIFY="${TEAMCTL_VERIFY:-1}"

# Allow `--version vX.Y.Z` as a positional flag for parity with cargo-dist's
# generated installer.
while [ $# -gt 0 ]; do
  case "$1" in
    --version) VERSION="$2"; shift 2 ;;
    --version=*) VERSION="${1#--version=}"; shift ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

case "$OS-$ARCH" in
  linux-x86_64)   TARGET=x86_64-unknown-linux-gnu ;;
  linux-aarch64)  TARGET=aarch64-unknown-linux-gnu ;;
  linux-arm64)    TARGET=aarch64-unknown-linux-gnu ;;
  darwin-x86_64)  TARGET=x86_64-apple-darwin ;;
  darwin-arm64)   TARGET=aarch64-apple-darwin ;;
  *) echo "unsupported platform: $OS-$ARCH" >&2; exit 1 ;;
esac

if [ "$VERSION" = "latest" ]; then
  release_json="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest")"
  # Anchor on the `"tag_name":` field name. A heuristic that grabs
  # the last quoted string on the line breaks on single-line JSON
  # (the last quoted string is usually body content, not the tag).
  if command -v jq >/dev/null 2>&1; then
    VERSION="$(printf '%s' "$release_json" | jq -r '.tag_name')"
  else
    VERSION="$(printf '%s' "$release_json" \
              | sed -nE 's/.*"tag_name": *"([^"]+)".*/\1/p' | head -1)"
  fi
  if [ -z "$VERSION" ] || [ "$VERSION" = "null" ]; then
    echo "could not resolve latest release tag from GitHub API" >&2
    exit 1
  fi
fi

# Pick a sha256 tool once. macOS ships shasum; most Linux distros ship sha256sum.
SHA_CMD=""
if [ "$VERIFY" != "0" ]; then
  if command -v sha256sum >/dev/null 2>&1; then
    SHA_CMD="sha256sum"
  elif command -v shasum >/dev/null 2>&1; then
    SHA_CMD="shasum -a 256"
  else
    echo "no sha256 tool on PATH (looked for sha256sum, shasum)" >&2
    echo "set TEAMCTL_VERIFY=0 to skip verification (not recommended)" >&2
    exit 1
  fi
fi

mkdir -p "$INSTALL_DIR"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT INT TERM

echo "installing teamctl $VERSION ($TARGET) -> $INSTALL_DIR"

# cargo-dist publishes one tarball per crate; each contains a single binary
# plus README/LICENSE. Pull all three.
installed=0
for bin in teamctl team-mcp team-bot; do
  tarball="$bin-$TARGET.tar.xz"
  url="https://github.com/$REPO/releases/download/$VERSION/$tarball"
  sums_url="$url.sha256"

  echo "  fetching $tarball"
  curl -fsSL "$url" -o "$tmp/$tarball"

  if [ "$VERIFY" != "0" ]; then
    if curl -fsSL "$sums_url" -o "$tmp/$tarball.sha256" 2>/dev/null; then
      expected="$(awk '{print $1}' "$tmp/$tarball.sha256")"
      actual="$(cd "$tmp" && $SHA_CMD "$tarball" | awk '{print $1}')"
      if [ "$expected" != "$actual" ]; then
        echo "sha256 mismatch for $tarball" >&2
        echo "  expected: $expected" >&2
        echo "  actual:   $actual" >&2
        exit 1
      fi
    else
      echo "sha256 sidecar not found at $sums_url" >&2
      echo "release may pre-date checksum publishing; set TEAMCTL_VERIFY=0 to skip" >&2
      exit 1
    fi
  fi

  tar -xJf "$tmp/$tarball" -C "$tmp"
  src="$tmp/$bin-$TARGET/$bin"
  if [ ! -x "$src" ]; then
    echo "tarball $tarball did not contain expected binary $bin" >&2
    exit 1
  fi
  install -m 0755 "$src" "$INSTALL_DIR/$bin"
  installed=$((installed + 1))
done

if [ "$VERIFY" != "0" ]; then
  echo "all sha256s verified."
fi
echo "installed $installed binaries to $INSTALL_DIR."

# T-070: if INSTALL_DIR isn't on PATH, print an actionable shell-tailored
# one-liner instead of a vague "make sure it's on your PATH." Friendly
# without auto-mutating rc files (per T-062).
case ":${PATH:-}:" in
  *":$INSTALL_DIR:"*)
    # Already on PATH — nothing more to say.
    exit 0
    ;;
esac

# System-wide install dirs (running as root) are typically on PATH already;
# if INSTALL_DIR somehow isn't, keep the message generic rather than nudging
# operator rc files.
if [ "$(id -u 2>/dev/null || echo 1)" = "0" ]; then
  echo "note: $INSTALL_DIR is not on root's PATH — add it to your system profile."
  exit 0
fi

echo
echo "WARNING: $INSTALL_DIR is not on your PATH."
echo

case "${SHELL:-}" in
  */zsh)
    rcfile="$HOME/.zshrc"
    echo "To fix it, run:"
    echo "  echo 'export PATH=\"$INSTALL_DIR:\$PATH\"' >> $rcfile && source $rcfile"
    echo
    echo "Or add the line manually to $rcfile."
    ;;
  */bash)
    rcfile="$HOME/.bashrc"
    echo "To fix it, run:"
    echo "  echo 'export PATH=\"$INSTALL_DIR:\$PATH\"' >> $rcfile && source $rcfile"
    echo
    echo "Or add the line manually to $rcfile."
    ;;
  */fish)
    echo "To fix it, run:"
    echo "  fish_add_path $INSTALL_DIR"
    echo
    echo "(persists immediately — no need to source.)"
    ;;
  *)
    rcfile="$HOME/.profile"
    echo "To fix it, run:"
    echo "  echo 'export PATH=\"$INSTALL_DIR:\$PATH\"' >> $rcfile && . $rcfile"
    echo
    echo "Or add the line manually to $rcfile. Some shells (csh, tcsh)"
    echo "use different syntax — adapt accordingly."
    ;;
esac
