#!/bin/sh
# teamctl installer — downloads the latest release binary for the current
# platform and drops it in ~/.local/bin.
#
# Usage:
#     curl -sSf https://teamctl.run/install | sh
#     curl -sSf https://teamctl.run/install | sh -s -- --version v0.1.0
#
# The production version of this script is generated by cargo-dist on every
# release and hosted at https://teamctl.run/install. This file is the source
# of truth for the fallback and for local installs.

set -eu

REPO="Alireza29675/teamctl"
INSTALL_DIR="${TEAMCTL_INSTALL_DIR:-$HOME/.local/bin}"
VERSION="${TEAMCTL_VERSION:-latest}"

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

case "$OS-$ARCH" in
  linux-x86_64)   TARGET=x86_64-unknown-linux-gnu ;;
  linux-aarch64)  TARGET=aarch64-unknown-linux-gnu ;;
  linux-arm64)    TARGET=aarch64-unknown-linux-gnu ;;
  darwin-x86_64)  TARGET=x86_64-apple-darwin ;;
  darwin-arm64)   TARGET=aarch64-apple-darwin ;;
  *) echo "unsupported platform: $OS-$ARCH" >&2; exit 1 ;;
esac

if [ "$VERSION" = "latest" ]; then
  VERSION="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" \
            | grep '"tag_name":' | head -1 | sed -E 's/.*"([^"]+)".*/\1/')"
fi

URL="https://github.com/$REPO/releases/download/$VERSION/teamctl-$TARGET.tar.xz"
echo "installing teamctl $VERSION ($TARGET) -> $INSTALL_DIR"

mkdir -p "$INSTALL_DIR"
tmp="$(mktemp -d)"
curl -fsSL "$URL" -o "$tmp/teamctl.tar.xz"
tar -xJf "$tmp/teamctl.tar.xz" -C "$tmp"

# cargo-dist bundles every binary into one tarball; copy them all.
for bin in teamctl team-mcp team-bot; do
  if [ -f "$tmp/teamctl-$TARGET/$bin" ]; then
    install -m 0755 "$tmp/teamctl-$TARGET/$bin" "$INSTALL_DIR/$bin"
  fi
done

rm -rf "$tmp"
echo "installed. Make sure $INSTALL_DIR is on your PATH."
